vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|20 Jul 2001 17:00:26 -0000
vti_extenderversion:SR|4.0.2.3406
vti_cacheddtm:TX|20 Jul 2001 17:00:26 -0000
vti_filesize:IR|20799
vti_cachedlinkinfo:VX|Q|webnews.css S|images/top_l.jpg S|images/blank.gif S|IMAGES/bannerWelcome.gif S|images/blank.gif S|images/blank.gif S|Images/blank.gif S|/images/blank.gif A|IndexMenuLocation.asp H|SearchLocation.asp S|images/PlaceToStay.gif H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp S|images/Communication.gif H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp S|images/PlaceOfWorship.gif H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp S|images/Shopping.gif H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp S|images/PlaceToEat.gif H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp S|images/Entertainment.gif H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp S|images/Transport.gif H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp S|images/BookingOffice.gif H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp S|images/MedicalService.gif H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp S|images/Book.gif H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp S|images/TravelAgency.gif H|SearchLocation.asp H|SearchLocation.asp S|images/Museum.gif H|SearchLocation.asp H|SearchLocation.asp S|images/Bank.gif H|SearchLocation.asp H|SearchLocation.asp H|SearchLocation.asp
vti_cachedsvcrellinks:VX|FQUS|webnews.css FSUS|images/top_l.jpg FSUS|images/blank.gif FSUS|IMAGES/bannerWelcome.gif FSUS|images/blank.gif FSUS|images/blank.gif FSUS|Images/blank.gif NSUS|file:///images/blank.gif FAUS|IndexMenuLocation.asp FHUS|SearchLocation.asp FSUS|images/PlaceToStay.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FSUS|images/Communication.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FSUS|images/PlaceOfWorship.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FSUS|images/Shopping.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FSUS|images/PlaceToEat.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FSUS|images/Entertainment.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FSUS|images/Transport.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FSUS|images/BookingOffice.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FSUS|images/MedicalService.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FSUS|images/Book.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp FSUS|images/TravelAgency.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FSUS|images/Museum.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FSUS|images/Bank.gif FHUS|SearchLocation.asp FHUS|SearchLocation.asp FHUS|SearchLocation.asp
vti_cachedtitle:SR|Index Menu Location
vti_title:SR|Index Menu Location
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" alink="#0000FF" link="#0000FF" vlink="#0000FF">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=windows-1252 GENERATOR Microsoft\\ FrontPage\\ 4.0 ProgId FrontPage.Editor.Document
vti_progid:SR|FrontPage.Editor.Document
vti_generator:SR|Microsoft FrontPage 4.0
vti_backlinkinfo:VX|indexmenulocation.asp mainmenu.asp
